# Copyright 2018-2026 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# Gitlab CI file for Data Format spec

# All stages use the same Docker image, so there are no prerequisites
# Refer to the container by its SHA instead of the name, to prevent
# caching problems when updating the image.
# image: khronosgroup/docker-images:asciidoctor-spec.202506
image: khronosgroup/docker-images@sha256:f1ca671f3bdb10ad49e238b9bf28853088a21af49504498fc9084c9b4fea4762

# Specify which gitlab runner to use
default:
  tags:
    - khrmedium

# Verify repository license compliance
license-check:
  stage: build
  before_script:
    # Nothing, all prerequisites are in the Docker image
  script:
    - reuse lint
  allow_failure: false

# Build the Data Format specification in HTML and PDF form
spec-generate:
  stage: build
  before_script:
    # Nothing, all prerequisites are in the Docker image
  script:
    - NODE_PATH="/usr/lib/node_modules"
    - export NODE_PATH
    # Build the core-only spec, to catch some incorrect ifdef errors
    - ./makeSpec -clean -spec core -genpath gencore QUIET= -j${nproc} -Otarget html manhtmlpages
    # Build the HTML and PDF specs
    - make html pdf
  artifacts:
    when: always
    paths:
      - out/
    expire_in: 1 week
