// Copyright 2020-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= COPYING File for the KhronosGroup/DataFormat Project

== Licenses

The DataFormat repository uses several licenses.

* The source files (in asciidoctor and other formats) for the DataFormat
  Specification and supporting documentation are licensed under the Creative
  Commons Attribution 4.0 International License (SPDX license identifier
  "`CC-BY-4.0`").
* Header files, scripts, and other tooling used or generated as part of the
  build process are typically licensed under the Apache License, Version 2.0
  (SPDX license identifier "`Apache-2.0`").
* There are a few remaining files adopted from other open source projects,
  such as a copy of the KaTeX distribution.
  Such files continue under their original MIT licenses, or in a few cases,
  like link:scripts/htmldiff/htmldiff[`scripts/htmldiff/htmldiff`], had no
  license statement.
  We have not added SPDX license identifiers to such externally originated
  files.

Users outside Khronos who create and post DataFormat Specifications, whether
modified or not, should use the CC-BY-4.0 license on the *output* documents
(HTML, PDF, etc.) they generate.
This is the default when building the Specification.


== Frequently Asked Questions

Q: Why are the HTML and PDF Specifications posted on Khronos' website under
a license which is neither CC-BY nor Apache-2.0?

A: The Specifications posted by Khronos in the DataFormat Registry are
licensed under the proprietary Khronos Specification License.
Only these Specifications are Ratified by the Khronos Board of Promoters,
and therefore they are the only Specifications covered by the Khronos
Intellectual Property Rights Policy.


Q: Does Khronos allow the creation and distribution of modified versions of
the Data Format Specification, such as translations to other languages?

A: Yes. Such modified Specifications, since they are not created by Khronos,
should be placed under the CC-BY license. If you believe your modifications
are of general interest, consider contributing them back by making a pull
request (PR) in the KhronosGroup/DataFormat repository.


Q: Can I contribute changes to the Data Format Specification?

A: Yes, by opening an Issue or Pull Request (PR) on the
link:https://github.com/KhronosGroup/DataFormat[DataFormat] GitHub project.
You must execute a click-through Contributor License Agreement, which brings
your changes under the umbrella of the Khronos IP policy.


Q: Can you change the license on your files so they are compatible with my
license?

A: If you *require* GPL compatibility for use of Apache-2.0 licensed files
in our repository, please raise an issue identifying the files and the
reason for the request, and we will consider changing those specific files
to a dual Apache 2.0 - MIT license.

