// Copyright 2014-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

ifdef::env-github[]
:note-caption: :information_source:
endif::[]

= Khronos^(TM)^ Data Format Specification

The Khronos Data Format Specification describes a portable mechanism
for describing a wide range of image/texture formats and other forms
of data.
It solely describes the format of what may be considered to be a single
"`pixel`" or a repeating group of pixels considered to be a "`texture
block`".

A wide variety of incompatible mechanisms exist in the industry for
describing formats that may be supported by an API.
These mechanisms typically consist of a simple enumeration, and need
retrospectively supplementing by metadata.
It is therefore common for generic code which can handle multiple
ormats to require multiple large switch statements to distinguish
different features of the formats that it supports, and for the
handling of image metadata to be awkward or incomplete.
The intent of this specification is to provide a machine-readable
and precise description that directly incorporates most common
metadata, while being extensible to specific needs.

This specification also contains a detailed description of the
in-memory representation of a number of compressed texture formats,
and describes some common color spaces.


== Repository Structure

The link:https://github.com/KhronosGroup/DataFormat[DataFormat] repository,
and the equivalent internal Khronos tracking repository, contain sources for
the formal documentation of the Khronos Data Format Specification.
These include:

[options="compact"]
  * The Data Format Specification
  * The `khr_df.h` C header file
  * Related tools and scripts

The repository hosts a public issue tracker, and outside developers can file
proposed changes (Pull Requests) against the Specification, subject to
approval by Khronos.


== External Contributions

Khronos welcomes feedback in GitHub Issues, and proposed changes in GitHub
Pull Requests (PRs), but will not necessarily accept all such changes.

Please keep your issues and pull requests focused on solving a single
problem. Broader feedback that tries to solve multiple problems, or touches
many parts of the Specification at once, is difficult for Khronos to review
in a timely fashion.


== Branch Structure

The current Specification (Data Format 1.3) is maintained in the default
branch (currently `main`) of the repository.


== Directory Structure

The directory structure is as follows:

```
README.adoc           This file
BUILD.adoc            Documents how to build the specifications
CONTRIBUTING.adoc     Requirements for external contributions to the repository
COPYING.adoc          Copyright and licensing information
CODE_OF_CONDUCT.adoc  Code of Conduct
LICENSE.adoc          Summary of licenses used by files in the repository
Makefile              Makefile (see BUILD.adoc)
appendices/           Specification appendices
chapters/             Specification chapters
config/               Asciidoctor configuration, CSS, and index generator
images/               Images (figures, diagrams, icons)
out/                  Default directory for the generated documents
scripts/              Helper scripts used in specification, header, and reference page generation
```


== Building the Specification and Reference Pages

The document sources are marked up in Asciidoc format, and we use
`asciidoctor` and related toolchain components to generate output documents.
See link:BUILD.adoc[BUILD.adoc] for more information on installing the
toolchain and building the Specification.


== Generating Headers and Related Files

The `khr_df.h` C header file defines structures and enums for specifying the
layout of images in memory.
