// Copyright 2015-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Data Format Asciidoc Configuration Files

== Support for Math

Asciidoctor is customized to insert KaTeX `<script>` tags from
`math.js` for HTML5, and properly pass through math which has
`\begin{}\/end{}` delimiters instead of $$\[\]\(\).

For PDF builds, asciidoctor-mathematical is used to generate
images.

== Stylesheets

`khronos.css` is the stylesheet used for HTML output.
It is a slightly tweaked version of the Asciidoctor 'Colony' theme.

== Title Page Images

Asciidoctor requires use of `docinfo` files to get logos onto the title
page, and has very restrictive naming conventions forcing the
subdirectories:

* `dataformat/docinfo-header.html` - Khronos logo in docinfo HTML form
  (built from images/Khronos_RGB_June18.svg)
* `makedocinfologo` - script to convert SVG file to docinfo HTML file

== Asciidoctor Extensions

We use a number of Asciidoctor customizations written in Ruby, described
briefly below.

* `asciidoctor-mathematical-ext.rb` - make latexmath: blocks work in table cells
* `katex_replace.rb` - substitute KaTeX for MathJax in output HTML
* `loadable_html.rb` - add some status messages for slow-loading documents
* `open_listing_block.rb` - allow '----' as a nested open block delimiter when tagged by '[open]'
* `rouge-extend-css.rb` - override parts of the 'rouge' highlighter CSS
