Khronos^(TM)^ Data Format Specification utilities
=================================================

This directory contains helper utilities for the Khronos
data format specification.
These are provided as examples rather than being intended for
use in production code (they are not robust to all possible
input, even for legal data format descriptors), and no warranty
is provided.

interpretdfd.c provides the ability to interpret a data format
descriptor for simple formats, and provides a simplified
interface for these case.

createdfd.c contains helpers for converting from Vulkan format
enums to data format descriptors.

printdfd.c produces a (fairly) human-readable description of
the fields of a data format descriptor, intended to assist with
debugging.

makevkswitch.pl and makedfdtovk.pl generate code that can be
used to convert from Vulkan enums to data format descriptors
and back again; these should be run with the Vulkan header
(or the format enum subset of it) as input, since they
heuristically support formats named in the header rather
than being hard-wired.
Since the resulting code depends highly on heuristics to
identify existing format mappings, it is not robust against
descriptors which did not originate as a Vulkan format.
Note that only common color formats are supported; there's
no support for depth formats or multi-planar formats, for
example.

These utilities require access to vulkan.h for access to
VkFormat.
