# Copyright 2021-2026 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# GitHub CI file for Data Format spec
# See .gitlab-ci.yml for non-Actions comments and step dependencies.

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or manual dispatch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # When a pull request is opened from a local branch or fork
  pull_request:

jobs:
  license-check:
    name: Verify repository license compliance
    runs-on: ubuntu-latest
    container: khronosgroup/docker-images@sha256:f1ca671f3bdb10ad49e238b9bf28853088a21af49504498fc9084c9b4fea4762

    steps:
      - uses: actions/checkout@v5
      - name: REUSE license checker
        run: reuse lint

  spec-generate:
    name: Build the Data Format specification
    runs-on: ubuntu-latest
    container: khronosgroup/docker-images@sha256:f1ca671f3bdb10ad49e238b9bf28853088a21af49504498fc9084c9b4fea4762

    steps:
      - uses: actions/checkout@v5
      - name: Build the Data Format specification
        run: make html pdf
      - name: Package generated spec
        # https://github.com/actions/upload-artifact#limitations
        # upload-artifact would upload many different files individually to
        # GitHub, which can take a lot of time.
        # Tar it to upload just one large file instead.
        run: tar -cvf spec-outputs.tar out
      - name: Archive generated spec
        uses: actions/upload-artifact@v7
        with:
          name: spec-outputs
          path: spec-outputs.tar
